#ifndef APPROXIMATIONLIB_GLOBAL_H
#define APPROXIMATIONLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(APPROXIMATION_LIBRARY)
#define QTAPPROXLIB_EXPORT Q_DECL_EXPORT
#else
#define QTAPPROXLIB_EXPORT Q_DECL_IMPORT
#endif

#endif // APPROXIMATIONLIB_GLOBAL_H
